### ISSUE TITLE
gemini-1.5-pro model configured with gemini-1.0-pro-001 version

### ISSUE THREAD

**Issue by sisbell** [TheFireCo/genkit-plugins#85] opened 2024-06-11 23:19 UTC
**Affected plugin(s)**

- [ ] VertexAI

**Describe the bug**
In the VertexAI plugin (js/plugins/vertexai/src/gemini.ts) gemini-1.5-pro model is configured with the gemini-1.0-pro-001 version. It should be using version gemini-1.5-pro-001

```
export const gemini15Pro = modelRef({
  name: 'vertexai/gemini-1.5-pro',
  info: {
    label: 'Vertex AI - Gemini 1.5 Pro',
    versions: ['gemini-1.0-pro-001'],
    supports: {
      multiturn: true,
      media: true,
      tools: true,
      systemRole: true,
    },
  },
  configSchema: GeminiConfigSchema,
});
```

**Plugin(s) version:**
0.5.2

**Genkit version:**
0.5.2

**Comment by Dabolus** [comment] 2024-06-12 05:53
Hi, thanks for opening the issue. However, this repo contains the community maintained plugins (the ones starting with `genkitx-`, while the VertexAI plugin is an official Firebase plugin (the ones starting with `@genkit-ai/`). Anyways, I can confirm the issue is present in the official plugin. I opened a PR [here](https://github.com/firebase/genkit/pull/392) to fix it. I'll close this issue since it's not related to this repo, but feel free to open a new one in the official Genkit repo [here](https://github.com/firebase/genkit/issues) if you want to follow up.

**Closed by Dabolus** 2024-06-12 05:53 UTC
Labels: bug
